apiVersion: auth.svcimpl.com/v1alpha1
kind: AWSAuth
metadata:
  name: awsauth-sample
spec:
  # Add fields here
  aws_role: gls-deployer-role
  kubernetes_role: tools-deployer-role
  kubernetes_user_name: gls-dev-bar
  target_namespace: tools
